login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('', views.home, name='home'),
    path('logon', views.logon, name='logon'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

sns/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.contrib import auth
from django.shortcuts import redirect, render
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    if request.user.is_authenticated:
        username = request.user.username
    else:
        username = ""
    return render(request, "login/home.html", {'is_authenticated': request.user.is_authenticated, 'username': username})

def logon(request):
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            
            if user is not None:
                auth.login(request, user)
                return redirect('login:home')

    form = UserCreationForm()
    return render(request, 'login/logon.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('login:home')
        
    form = AuthenticationForm()
    return render(request, 'login/login.html', {'form': form})

def logout(request):
    auth.logout(request)
    return redirect('login:home')

login/templates/login/home.html
<body>
    <h1>Welcome {{ username }}</h1>
    {% if is_authenticated %}
        <button onclick="location.href='{% url 'login:logout' %}'">logout</button>
    {% else %}
        <button onclick="location.href='{% url 'login:logon' %}'">logon</button>
        <button onclick="location.href='{% url 'login:login' %}'">login</button>
    {% endif %}
</body>

login/templates/login/login.html
<body>
    <form action="{% url 'login:login' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
</body>

login/templates/login/logon.html
<body>
    <form action="{% url 'login:logon' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit">
    </form>
    <button onclick="location.href='{% url 'login:home' %}'">back to home</button>
</body>